---
title: Atividade 10
---
flowchart TD
    start([start])
    fim([end])
    conector@{shape: circle, label: " "}
    subgraph " "
        a@{shape: manual-input}
        b@{shape: manual-input}
        c@{shape: manual-input}
    end
    delta["$$\Delta = b^2 - 4ac$$"]
    x1["$$x_1 = \frac{-b+\sqrt{\Delta}}{2a}$$"]
    x2["$$x_2 = \frac{-b-\sqrt{\Delta}}{2a}$$"]
    subgraph Displays
        ddelta@{shape: display, label: "delta"}
        dx1@{shape: display, label: "x1"}
        dx2@{shape: display, label: "x2"}
        invalido@{shape: display, label: "\"Não possui raizes reais\""}
    end
    if{delta < 0}
    
    start --> a --> b --> c --> delta --> if

    if --> |true| invalido
    if --> |false| x1 --> x2 --> ddelta --> dx1 --> dx2 --> conector
    invalido --> conector

    conector --> fim